Update conferences.yml
abhshkdz/ai-deadlines pull request #320
Opened 2021-01-15 06:16 UTC by YoYoo-AI

update ACM mm 2021

2021-01-15 06:28 UTC, abhshkdz requested changes

2021-01-15 06:28 UTC, abhshkdz commented on _data/conferences.yml
> +  deadline: '2020-04-3 23:59:00'
Should this be 2021-04-03?

2021-01-15 06:28 UTC, abhshkdz commented on _data/conferences.yml
>    date: October 12-16, 2020
Please update this to 2021 dates

2021-01-20 01:50 UTC, YoYoo-AI commented on _data/conferences.yml
> +  deadline: '2020-04-3 23:59:00'
Yes, I have updated it.

2021-01-21 12:11 UTC, abhshkdz commented
Could you update the `date` field to 2021 please.

2021-01-22 10:23 UTC, merged

2021-01-22 10:23 UTC, abhshkdz commented
Nvm done; thanks!